name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Metadata to Salesforce Org
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli --global
          sfdx --version

- name: Authenticate with SFDX URL
  run: |
    echo "${{ secrets.SFDX_AUTH_URL }}" > sfdx_auth.txt
    sfdx force:auth:sfdxurl:store -f sfdx_auth.txt -a LeadlikeDevHub
    sfdx force:org:list

      - name: Deploy Metadata
        run: |
          sfdx force:source:deploy -p force-app -u LeadlikeDevHub --json --loglevel fatal
